// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mikhaylova_lr2.Data;

#nullable disable

namespace Mikhaylova_lr2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Mikhaylova_lr2.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupNumber = "АС-22-04"
                        },
                        new
                        {
                            Id = 2,
                            GroupNumber = "АС-22-05"
                        },
                        new
                        {
                            Id = 3,
                            GroupNumber = "АА-22-07"
                        });
                });

            modelBuilder.Entity("Mikhaylova_lr2.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Review")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("StudentId", "TeacherId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Mikhaylova_lr2.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Екатерина",
                            GroupId = 1,
                            LastName = "Михайлова",
                            MiddleName = "Сергеевна"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Екатерина",
                            GroupId = 1,
                            LastName = "Ткачева",
                            MiddleName = "Дмитриевна"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Никита",
                            GroupId = 1,
                            LastName = "Клейменов",
                            MiddleName = "Игоревич"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Иван",
                            GroupId = 2,
                            LastName = "Иванов",
                            MiddleName = "Иванович"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Просковья",
                            GroupId = 2,
                            LastName = "Простова",
                            MiddleName = "Петровна"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Геннадий",
                            GroupId = 3,
                            LastName = "Громов",
                            MiddleName = "Васильевич"
                        });
                });

            modelBuilder.Entity("Mikhaylova_lr2.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Татьяна",
                            LastName = "Михайлова",
                            MiddleName = "Папилина"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Антон",
                            LastName = "Тупысев",
                            MiddleName = "Михайлович"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Александр",
                            LastName = "Асирян",
                            MiddleName = "Вячеславович"
                        });
                });

            modelBuilder.Entity("Mikhaylova_lr2.Models.TeacherGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeacherId", "GroupId")
                        .IsUnique();

                    b.ToTable("TeacherGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 1,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            GroupId = 2,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            GroupId = 3,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 5,
                            GroupId = 3,
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("Mikhaylova_lr2.Models.Rating", b =>
                {
                    b.HasOne("Mikhaylova_lr2.Models.Student", "Student")
                        .WithMany("Ratings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mikhaylova_lr2.Models.Teacher", "Teacher")
                        .WithMany("Ratings")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Mikhaylova_lr2.Models.Student", b =>
                {
                    b.HasOne("Mikhaylova_lr2.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mikhaylova_lr2.Models.TeacherGroup", b =>
                {
                    b.HasOne("Mikhaylova_lr2.Models.Group", "Group")
                        .WithMany("TeacherGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mikhaylova_lr2.Models.Teacher", "Teacher")
                        .WithMany("TeacherGroups")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Mikhaylova_lr2.Models.Group", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("TeacherGroups");
                });

            modelBuilder.Entity("Mikhaylova_lr2.Models.Student", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Mikhaylova_lr2.Models.Teacher", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("TeacherGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
